---
- name: publish new version of content view
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    organization: undef
    lifecycle_environment: undef
    content_view: undef

  tasks:
  - name: Publish Content View
    redhat.satellite.content_view_version:
      content_view: "{{ content_view }}"
      organization: "{{ organization }}"
      lifecycle_environments: "{{ lifecycle_environment }}"
